apiRules:
- exclude:
    uidRegex: ^DevExtreme\.AspNet\.Data\.Helpers\.Compat$
- exclude:
    uidRegex: ^DevExtreme\.AspNet\.Data\.DataSourceLoadOptionsBase\.(Pre|Remote)Select$
- exclude:
    uidRegex: ^System\.Object\.
